// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/Eagle233Fake/omniread/backend/application/service/auth"
	"github.com/Eagle233Fake/omniread/backend/infra/cache"
	"github.com/Eagle233Fake/omniread/backend/infra/config"
	"github.com/Eagle233Fake/omniread/backend/infra/repo"
)

// Injectors from wire.go:

func NewProvider() (*Provider, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	database := GetDB(configConfig)
	userRepo := repo.NewUserRepo(database)
	redis := GetRedis(configConfig)
	authCache := cache.NewAuthCache(redis)
	authService := auth.NewAuthService(userRepo, authCache)
	providerProvider := &Provider{
		Config:      configConfig,
		AuthService: authService,
	}
	return providerProvider, nil
}
